<?php
/**
 * Morningtime Internetkassa extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Morningtime
 * @package    Morningtime_Internetkassa
 * @copyright  Copyright (c) 2009 Morningtime Internet, http://www.morningtime.com
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php echo $this->__('Paid with Ogone') ?>
    {{pdf_row_separator}}
<?php if($this->getIssuerPaymentMethod()->getValue()){ ?>
	<?php print $this->__('Card type'); ?>: <?php echo $this->getPaymentMethod()->getValue(); ?>
<?php } ?>
