<?php
/**
 * Morningtime Internetkassa extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Morningtime
 * @package    Morningtime_Internetkassa
 * @copyright  Copyright (c) 2009 Morningtime Internet, http://www.morningtime.com
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if($_info = $this->getInfo()): ?>
<p><?php print $this->__('Paid with Ogone'); ?></p>
<?php if($_info->getIssuerPaymentMethod()){ ?>
<p><?php print $this->__('Card type'); ?>: <?php echo $_info->getPaymentMethod()->getValue(); ?></p>
<p><?php print $this->__('Processor'); ?>: <?php echo $_info->getPaymentMethod()->getBrand(); ?></p>
<?php } ?>
<?php else: ?>
<?php endif; ?>
